PROJECT: docker_test

# general settings
NV_GPU: 0
LOG_DIR_PATH: logs
MODEL_DIR_PATH: models
DATA_DIR_PATH: data
JUPYTER_NOTEBOOK_PORT: 8899
TENSORBOARD_PORT: 9988

# model settings
TARGET_IMAGE_SIZE: 224
BATCH_SIZE: 128
EPOCHS: 100
PATIENCE: 5
BASE_MODEL_NAME: resnet50
OPTIMIZER:
 METHOD: SGD
 LR: 1e-4
 MOMENTUM: 0.9
L2: 0.001
DROPOUT: 0.5
MODEL_NAME: dokusho_analysis
WORKERS: 6

